const picks=[9,20,37,48,65,76,93,104,121,132,149,160,177,188,205,216],key='pick9-hosted-v1';
let state={selected:[],gone:[],retired:[],more:0},history=[];
try{state=Object.assign(state,JSON.parse(localStorage.getItem(key)||'{}'))}catch(e){}
const byId=Object.fromEntries(players.map(p=>[p.id,p]));
const el=id=>document.getElementById(id),team=()=>state.selected.map(id=>byId[id]).filter(Boolean),round=()=>state.selected.length+1;
function counts(t=team()){const c={QB:0,RB:0,WR:0,TE:0,DEF:0,K:0};t.forEach(p=>c[p.pos]++);return c}
function build(t=team()){return t.length?t.map(p=>p.pos).join('–'):'Empty'}
function pickLabel(r){return `${r}.${r%2?9:6}`}
function plan(r=round(),t=team()){const c=counts(t);if(r===1)return'Choose the best elite RB or WR still available';if(r===2)return c.RB?'Prefer a premium RB2; take an elite WR faller':'Prioritize your first premium RB';if(r<=4)return c.RB<2?'RB is the priority unless WR value falls':c.WR<2?'Build your starting WR core':'Take the best RB/WR value';if(r<=6)return c.WR<3?'Add WR/FLEX depth':c.QB<1&&r===6?'This is a strong quarterback window':c.TE<1?'Consider TE value or add RB/WR':'Best RB/WR value';if(r<=8)return c.QB<1?'Draft your starting QB now':c.TE<1?'Fill TE or add upside RB/WR':'Add upside RB/WR depth';if(r<=10&&c.TE<1)return'Draft a tight end before the tier dries up';if(r<15)return'Bench upside: contingent RBs and breakout WRs';return r===15?'Draft a defense':'Draft a kicker'}
function need(p,r,c){let s=0;if(c.QB&&p.pos==='QB')s-=50;if(c.TE&&p.pos==='TE')s-=24;if(r===1)s+=p.pos==='RB'?13:p.pos==='WR'?11:-60;else if(r===2)s+=c.RB?(p.pos==='RB'?17:p.pos==='WR'?14:-35):(p.pos==='RB'?28:-12);else if(r<=4){if(c.RB<2&&p.pos==='RB')s+=23;if(c.WR<2&&p.pos==='WR')s+=23;if(['QB','TE'].includes(p.pos))s-=14}else if(r<=6){if(c.RB<2&&p.pos==='RB')s+=21;if(c.WR<3&&p.pos==='WR')s+=16;if(c.QB<1&&p.pos==='QB')s+=r===6?17:4;if(c.TE<1&&p.pos==='TE')s+=10}else if(r<=8){if(c.QB<1&&p.pos==='QB')s+=38;if(c.TE<1&&p.pos==='TE')s+=18;if(['RB','WR'].includes(p.pos))s+=8}else if(r<=10){if(c.TE<1&&p.pos==='TE')s+=40;if(c.QB<1&&p.pos==='QB')s+=25;if(['RB','WR'].includes(p.pos))s+=10}else if(r<15)s+=['RB','WR'].includes(p.pos)?25:-45;else s+=r===15?(p.pos==='DEF'?110:-110):(p.pos==='K'?110:-110);return s}
function ranked(r=round()){const pick=picks[r-1],c=counts(),blocked=new Set([...state.selected,...state.gone,...state.retired.flat()]);return players.filter(p=>!blocked.has(p.id)).filter(p=>{if(r===15)return p.pos==='DEF';if(r===16)return p.pos==='K';if(['DEF','K'].includes(p.pos))return false;return r===1?p.adp<30:p.adp>=pick-23&&p.adp<=pick+54}).map(p=>({p,score:48-Math.abs(p.adp-pick)*.55+Math.max(-14,Math.min(24,(pick-p.adp)*1.25))+need(p,r,c)})).sort((a,b)=>b.score-a.score||a.p.adp-b.p.adp).map(x=>x.p)}
function save(){try{localStorage.setItem(key,JSON.stringify(state))}catch(e){}}
function snapshot(){history.push(JSON.stringify(state));if(history.length>40)history.shift()}
function reason(p,r,i){const c=counts(),out=[];if(i===0)out.push('Top recommendation');if(p.adp<picks[r-1])out.push('value at this pick');if(p.pos==='RB'&&c.RB<2)out.push('fills scarce RB slot');if(p.pos==='WR'&&c.WR<3)out.push('builds WR/FLEX');if(p.pos==='QB'&&!c.QB)out.push('secures starting QB');if(p.pos==='TE'&&!c.TE)out.push('fills TE');return(out.length?out:['best roster fit']).join(' · ')}
function render(scroll=false){const t=team(),r=round();let html='<div class="root">Your draft path<small>Every click changes the recommendations below.</small></div>';t.forEach((p,i)=>{const rr=i+1;html+=`<section class="node"><div class="node-row"><div class="round"><b>R${rr}</b><small>${pickLabel(rr)} · #${picks[i]}</small></div><div class="player"><b>${p.name} · ${p.pos}</b><small>ADP ${p.adp}</small></div><button class="change" data-edit="${i}">Change</button></div><div class="effect">Next: ${plan(rr+1,t.slice(0,i+1))}</div></section>`});if(r<=16){const all=ranked(r),show=all.slice(0,(r===1?12:6)+state.more);html+=`<section class="branch" id="branch"><div class="branch-title"><small>ROUND ${r} · ${pickLabel(r)} · OVERALL ${picks[r-1]}</small><h2>${plan()}</h2><p>Tap the player you actually draft. Tap Gone when another manager selects one.</p></div><div class="cards">${show.map((p,i)=>`<article class="card ${i===0?'best':''}"><button class="draft" data-pick="${p.id}"><div class="card-top"><div class="pos">${p.pos}</div><div class="card-name"><b>${p.name}</b><small>ADP ${p.adp}</small></div><span class="rank">${i===0?'BEST FIT':`OPTION ${i+1}`}</span></div><div class="why">${reason(p,r,i)}</div><div class="next">If selected → ${r===16?'Draft complete':plan(r+1,[...t,p])}</div></button><div class="card-foot"><span>Tap card to draft</span><button class="gone" data-gone="${p.id}">Gone</button></div></article>`).join('')}</div><div class="tools">${show.length<all.length?'<button class="tool" id="more">Show more</button>':''}${state.gone.length?'<button class="tool" id="restore">Restore last Gone</button>':''}</div></section>`}else html+='<section class="done"><h2>Draft complete</h2><p>Your roster is saved on this device.</p></section>';el('tree').innerHTML=html;el('status').innerHTML=`<span class="pill"><b>${r<=16?'Round '+r:'Complete'}</b></span>${r<=16?`<span class="pill">Pick <b>${pickLabel(r)} / #${picks[r-1]}</b></span>`:''}<span class="pill">Path <b>${build(t)}</b></span>`;const c=counts(t);el('construction').textContent=build(t);el('team').innerHTML=`<div class="counts">${Object.keys(c).map(k=>`<span><b>${c[k]}</b> ${k}</span>`).join('')}</div><div class="roster">${t.map((p,i)=>`R${i+1}: <b>${p.name}</b> (${p.pos})`).join('<br>')||'No picks yet'}</div>`;bind();el('undo').disabled=!history.length;if(scroll)setTimeout(()=>el('branch')?.scrollIntoView({block:'start'}),20)}
function bind(){document.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{const id=+b.dataset.pick,r=round(),list=ranked(r),index=list.findIndex(p=>p.id===id);snapshot();state.retired[r-1]=list.slice(0,index).map(p=>p.id);state.selected.push(id);state.more=0;save();render(true)});document.querySelectorAll('[data-gone]').forEach(b=>b.onclick=e=>{e.stopPropagation();snapshot();state.gone.push(+b.dataset.gone);save();render()});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{snapshot();const i=+b.dataset.edit;state.selected=state.selected.slice(0,i);state.retired=state.retired.slice(0,i);state.more=0;save();render(true)});const more=el('more'),restore=el('restore');if(more)more.onclick=()=>{snapshot();state.more+=6;save();render()};if(restore)restore.onclick=()=>{snapshot();state.gone.pop();save();render()}}
el('undo').onclick=()=>{if(history.length){state=JSON.parse(history.pop());save();render()}};el('reset').onclick=()=>{if(confirm('Reset the full draft tree?')){snapshot();state={selected:[],gone:[],retired:[],more:0};save();render(true)}};render();
